---
- name: Restart Nginx Service
  hosts: webservers
  become: true

  tasks:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Verify Nginx Status
      service:
        name: nginx
        state: started